id: I04E035F0
ocr_import_info:
  source: bdrc
  software: google_books
  batch: batch_2022
  expected_default_language: bo
  bdrc_scan_id: W3CN1548
  ocr_info:
    timestamp: 03/21/23T14:08:29
    html: html.zip
    txt: txt.zip
    images: images.zip
  op_import_options: {}
  op_import_version: 0.11.9
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-02-28 22:00:41.999352+00:00
last_modified: 2024-02-28 22:00:41.999359+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN1548
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN1548
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཆགས་མེད་བདེ་སྨོན།
  languages:
  - bo
  author: གནས་མདོ་ཀརྨ་ཆགས་མེད།
statistics:
  ocr_word_mean_confidence_index: 0.9703571428571428
  ocr_word_median_confidence_index: 0.985
bases:
  I3CN1550:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN1550
      total_pages: 30
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN1550.txt
    statistics:
      ocr_word_median_confidence_index: 0.985
      ocr_word_mean_confidence_index: 0.9703571428571428
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
